# Generated by Django 4.0.3 on 2022-04-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_instance_predecessor_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_instance_current_task',
            name='current_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_task_workflow_instance_current_task', to='app.task_instance'),
        ),
    ]
