# Generated by Django 4.0.3 on 2022-04-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_instance_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_instance',
            name='instance_name',
            field=models.CharField(default='workflow_instance', max_length=100),
        ),
    ]
