# Generated by Django 4.0.3 on 2022-04-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_workflow_instance_instance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='workflow_id',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='workflow_id',
        ),
    ]
