# Generated by Django 4.0.3 on 2022-04-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_role_workflow_id_remove_user_role_workflow_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_worklow', to=settings.AUTH_USER_MODEL)),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_user', to='app.workflow')),
            ],
        ),
    ]
